name: Crypto Edge Auto Bot

'on':
workflow_dispatch:
schedule:
- cron: '0 * * * *'

jobs:
test:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Run Market Update and Crypto News
env:
TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
run: |
pip install requests
python bot.py
python news.py
