name: Crypto Edge Market Sentiment

'on':
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

permissions:
  contents: read

jobs:
  sentiment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Requests
        run: pip install requests

      - name: Run Market Sentiment
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python sentiment.py
